FROM n8nio/n8n:latest

ENV DB_TYPE=postgresdb
ENV DATABASE_URL=postgresql://postgres:${PGPASSWORD}@postgres.railway.internal:5432/railway?sslmode=no-verify
ENV WEBHOOK_URL=https://${RAILWAY_STATIC_URL}

# Configuración básica de n8n
ENV N8N_PORT=5678
ENV NODE_ENV=production
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

# Configuración de seguridad
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false

EXPOSE 5678
